Repository palantir/witchcraft-go-server, pull requests merged in 2020-11, with the labels that each got.

#222 Bump godel-conjure-plugins to v6
  changelog/@unreleased/pr-222.v2.yml
  conjure/witchcraft/api/health/enums.conjure.go
  godel/config/godel.yml
  integration/health_test.go
  integration/ratelimit_test.go
  integration/server_test.go
  status/diagnostic_logging_change_handler.go
  status/diagnostic_logging_change_handler_test.go
  status/health/heartbeat/source.go
  status/health/heartbeat/source_test.go
  status/health/periodic/options_test.go
  status/health/periodic/source.go
  status/health/periodic/source_test.go
  status/health/refreshable/source_test.go
  status/health/store/keyed_error_source.go
  status/health/store/keyed_error_source_test.go
  status/health/tree/tree.go
  status/health/tree/tree_test.go
  status/health/utils.go
  status/health/window/error_source_test.go
  status/health/window/key_error_source.go
  status/health/window/key_error_source_test.go
  status/reporter/healthcomponent.go
  status/reporter/healthcomponent_test.go
  status/reporter/healthreporter.go
  status/reporter/healthreporter_test.go
  status/routes/routes_test.go
  status/status.go
  status/status_test.go
  witchcraft/ratelimit/middleware.go
  witchcraft/server_state.go
Labels: merge when ready

#225 Bump import paths in README to v2
  README.md
Labels: merge when ready, no changelog

#224 Break: Move ValidatingRefreshableHealthCheckSource to internal package
  changelog/@unreleased/pr-224.v2.yml
  witchcraft/internal/refreshable/source.go
  witchcraft/internal/refreshable/source_test.go
  witchcraft/witchcraft.go
Labels: merge when ready

#226 Delete extra bulldozer.yml
  .palantir/bulldozer.yml
Labels: merge when ready, no changelog

#227 Break: Finish migration of health libraries to witchcraft-go-health
  changelog/@unreleased/pr-227.v2.yml
  go.mod
  go.sum
  godel/config/conjure-plugin.yml
  integration/health_test.go
  integration/ratelimit_test.go
  integration/server_test.go
  status/change_handler.go
  status/diagnostic_logging_change_handler.go
  status/diagnostic_logging_change_handler_test.go
  status/health/heartbeat/source.go
  status/health/heartbeat/source_test.go
  status/health/periodic/options_test.go
  status/health/periodic/source_test.go
  status/health/store/keyed_error_source.go
  status/health/store/keyed_error_source_test.go
  status/health/tree/tree.go
  status/health/tree/tree_test.go
  status/health/window/base_source.go
  status/health/window/error_source.go
  status/health/window/error_source_test.go
  status/health/window/key_error_source.go
  status/health/window/key_error_source_test.go
  status/health/window/time_provider.go
  status/health/window/time_windowed_store.go
  status/health/window/time_windowed_store_test.go
  status/health/window/timed_key_store.go
  status/health/window/timed_key_store_test.go
  status/logging_change_handler.go
  status/logging_change_handler_test.go
  status/multi_change_handler.go
  status/reporter/healthcomponent_test.go
  status/reporter/healthreporter_test.go
  status/reporter/readinessreporter_test.go
  status/routes/routes.go
  status/routes/routes_test.go
  status/status.go
  status/status_test.go
  vendor/github.com/palantir/witchcraft-go-health/LICENSE
  vendor/github.com/palantir/witchcraft-go-health/conjure/witchcraft/api/health/aliases.conjure.go
  vendor/github.com/palantir/witchcraft-go-health/conjure/witchcraft/api/health/enums.conjure.go
  vendor/github.com/palantir/witchcraft-go-health/conjure/witchcraft/api/health/structs.conjure.go
  vendor/github.com/palantir/witchcraft-go-health/reporter/healthcomponent.go
  vendor/github.com/palantir/witchcraft-go-health/reporter/healthreporter.go
  vendor/github.com/palantir/witchcraft-go-health/reporter/readinesscomponent.go
  vendor/github.com/palantir/witchcraft-go-health/reporter/readinessreporter.go
  vendor/github.com/palantir/witchcraft-go-health/sources/periodic/option.go
  vendor/github.com/palantir/witchcraft-go-health/sources/periodic/source.go
  vendor/github.com/palantir/witchcraft-go-health/sources/utils.go
  vendor/github.com/palantir/witchcraft-go-health/status/status.go
  vendor/modules.txt
  witchcraft/internal/refreshable/source.go
  witchcraft/internal/refreshable/source_test.go
  witchcraft/ratelimit/middleware.go
  witchcraft/server_routes.go
  witchcraft/server_state.go
  witchcraft/witchcraft.go
Labels: merge when ready

#230 Bump witchcraft-go-health to latest
  go.mod
  go.sum
  vendor/github.com/palantir/witchcraft-go-health/conjure/witchcraft/api/health/enums.conjure.go
  vendor/modules.txt
Labels: autorelease, merge when ready, no changelog

#216 Add WitchcraftDebugService routes
  README.md
  changelog/@unreleased/pr-216.v2.yml
  config/runtime.go
  go.sum
  witchcraft/internal/wdebug/handlers.go
  witchcraft/internal/wdebug/resource.go
  witchcraft/internal/wdebug/resource_test.go
  witchcraft/server_routes.go
Labels: autorelease, merge when ready
