Repository palantir/witchcraft-go-server, pull requests merged in 2021-03, with the labels that each got.

#251 Add TCP logging output
  changelog/@unreleased/pr-251.v2.yml
  go.mod
  go.sum
  vendor/github.com/rs/zerolog/.gitignore
  vendor/github.com/rs/zerolog/.travis.yml
  vendor/github.com/rs/zerolog/CNAME
  vendor/github.com/rs/zerolog/LICENSE
  vendor/github.com/rs/zerolog/README.md
  vendor/github.com/rs/zerolog/_config.yml
  vendor/github.com/rs/zerolog/array.go
  vendor/github.com/rs/zerolog/console.go
  vendor/github.com/rs/zerolog/context.go
  vendor/github.com/rs/zerolog/ctx.go
  vendor/github.com/rs/zerolog/encoder.go
  vendor/github.com/rs/zerolog/encoder_cbor.go
  vendor/github.com/rs/zerolog/encoder_json.go
  vendor/github.com/rs/zerolog/event.go
  vendor/github.com/rs/zerolog/fields.go
  vendor/github.com/rs/zerolog/globals.go
  vendor/github.com/rs/zerolog/go.mod
  vendor/github.com/rs/zerolog/go.sum
  vendor/github.com/rs/zerolog/go112.go
  vendor/github.com/rs/zerolog/hook.go
  vendor/github.com/rs/zerolog/internal/cbor/README.md
  vendor/github.com/rs/zerolog/internal/cbor/base.go
  vendor/github.com/rs/zerolog/internal/cbor/cbor.go
  vendor/github.com/rs/zerolog/internal/cbor/decode_stream.go
  vendor/github.com/rs/zerolog/internal/cbor/string.go
  vendor/github.com/rs/zerolog/internal/cbor/time.go
  vendor/github.com/rs/zerolog/internal/cbor/types.go
  vendor/github.com/rs/zerolog/internal/json/base.go
  vendor/github.com/rs/zerolog/internal/json/bytes.go
  vendor/github.com/rs/zerolog/internal/json/string.go
  vendor/github.com/rs/zerolog/internal/json/time.go
  vendor/github.com/rs/zerolog/internal/json/types.go
  vendor/github.com/rs/zerolog/log.go
  vendor/github.com/rs/zerolog/not_go112.go
  vendor/github.com/rs/zerolog/pretty.png
  vendor/github.com/rs/zerolog/sampler.go
  vendor/github.com/rs/zerolog/syslog.go
  vendor/github.com/rs/zerolog/writer.go
  vendor/modules.txt
  witchcraft/internal/tcpjson/conn_provider.go
  witchcraft/internal/tcpjson/conn_provider_test.go
  witchcraft/internal/tcpjson/envelope.go
  witchcraft/internal/tcpjson/tcp_logger.go
  witchcraft/internal/tcpjson/tcp_logger_test.go
  witchcraft/loggers.go
  witchcraft/witchcraft.go
Labels: merge when ready

#253 Collect all internal and user defined health check sources
  witchcraft/server_routes.go
  witchcraft/witchcraft.go
Labels: merge when ready, no changelog

#255 improvement: Add TCPWriter health check source
  changelog/@unreleased/pr-255.v2.yml
  vendor/github.com/palantir/witchcraft-go-health/sources/window/base_source.go
  vendor/github.com/palantir/witchcraft-go-health/sources/window/error_options.go
  vendor/github.com/palantir/witchcraft-go-health/sources/window/error_source.go
  vendor/github.com/palantir/witchcraft-go-health/sources/window/error_source_deprecated.go
  vendor/github.com/palantir/witchcraft-go-health/sources/window/key_error_deprecated.go
  vendor/github.com/palantir/witchcraft-go-health/sources/window/key_error_source.go
  vendor/github.com/palantir/witchcraft-go-health/sources/window/time_provider.go
  vendor/github.com/palantir/witchcraft-go-health/sources/window/time_windowed_store.go
  vendor/github.com/palantir/witchcraft-go-health/sources/window/timed_key_store.go
  vendor/modules.txt
  witchcraft/internal/tcpjson/tcp_logger.go
  witchcraft/internal/tcpjson/tcp_logger_test.go
  witchcraft/witchcraft.go
Labels: merge when ready

#258 Only enable TCP logging if both log metadata and receiver are configured
  changelog/@unreleased/pr-258.v2.yml
  witchcraft/internal/tcpjson/envelope.go
  witchcraft/internal/tcpjson/tcp_logger.go
  witchcraft/internal/tcpjson/tcp_logger_test.go
  witchcraft/witchcraft.go
Labels: merge when ready

#260 Set the TCP logger connection health status to a WARNING state on errors
  go.mod
  go.sum
  vendor/github.com/palantir/witchcraft-go-health/sources/window/error_options.go
  vendor/github.com/palantir/witchcraft-go-health/sources/window/error_source.go
  vendor/modules.txt
  witchcraft/internal/tcpjson/tcp_logger.go
  witchcraft/internal/tcpjson/tcp_logger_test.go
Labels: merge when ready, no changelog

#259 Refactor RouteParam interface to use builder pattern
  changelog/@unreleased/pr-259.v2.yml
  wrouter/route_params.go
  wrouter/router_root.go
Labels: merge when ready

#257 Skip logging telemetry on liveness, readiness, health routes.
  changelog/@unreleased/pr-257.v2.yml
  status/routes/routes.go
  witchcraft/internal/middleware/request.go
  witchcraft/internal/middleware/request_test.go
  witchcraft/internal/middleware/route.go
  wrouter/route_params.go
  wrouter/router.go
  wrouter/router_root.go
Labels: autorelease, merge when ready

#261 Emit an error log instead of setting the TCPWriter health state to warning
  changelog/@unreleased/pr-261.v2.yml
  witchcraft/witchcraft.go
Labels: autorelease, merge when ready

#262 feature: TCP writer uses a buffered channel to queue messages
  changelog/@unreleased/pr-262.v2.yml
  witchcraft/internal/tcpjson/async_writer.go
  witchcraft/internal/tcpjson/async_writer_test.go
  witchcraft/witchcraft.go
Labels: autorelease, merge when ready

#264 Fix async writer to no longer retain the provided byte slice
  witchcraft/internal/tcpjson/async_writer.go
  witchcraft/internal/tcpjson/async_writer_test.go
  witchcraft/internal/tcpjson/tcp_logger_test.go
Labels: merge when ready, no changelog

#266 fix: update WGL to latest and update relevant tests with logging changes
  changelog/@unreleased/pr-266.v2.yml
  go.mod
  go.sum
  vendor/github.com/palantir/witchcraft-go-logging/conjure/witchcraft/api/logging/enums.conjure.go
  vendor/github.com/palantir/witchcraft-go-logging/wlog-zap/internal/marshalers/wtracing_spanmodel.go
  vendor/github.com/palantir/witchcraft-go-logging/wlog/trclog/trc1log/params.go
  vendor/github.com/palantir/witchcraft-go-tracing/wtracing/span.go
  vendor/github.com/palantir/witchcraft-go-tracing/wzipkin/span.go
  vendor/modules.txt
  witchcraft/internal/tcpjson/async_writer_test.go
  witchcraft/internal/tcpjson/tcp_logger_test.go
  witchcraft/witchcraft_test.go
Labels: merge when ready

#265 improvement: add http tags to request middleware
  changelog/@unreleased/pr-265.v2.yml
  go.mod
  go.sum
  vendor/github.com/palantir/witchcraft-go-logging/wlog/logreader/reader.go
  vendor/github.com/palantir/witchcraft-go-tracing/wtracing/context.go
  vendor/github.com/palantir/witchcraft-go-tracing/wtracing/span.go
  vendor/github.com/palantir/witchcraft-go-tracing/wzipkin/span.go
  vendor/modules.txt
  witchcraft/internal/middleware/request.go
  witchcraft/internal/middleware/request_test.go
Labels: autorelease, merge when ready

#267 TCPWriter: Close connections on network timeout errors
  changelog/@unreleased/pr-267.v2.yml
  witchcraft/internal/tcpjson/tcp_logger.go
  witchcraft/internal/tcpjson/tcp_logger_test.go
Labels: merge when ready

#270 Update logging queue metric name to match java
  witchcraft/internal/tcpjson/async_writer.go
Labels: merge when ready, no changelog

#273 Use the witchcraft-go-logging TCP logger implementation
  go.mod
  vendor/github.com/palantir/witchcraft-go-logging/wlog/tcpjson/async_writer.go
  vendor/github.com/palantir/witchcraft-go-logging/wlog/tcpjson/conn_provider.go
  vendor/github.com/palantir/witchcraft-go-logging/wlog/tcpjson/conn_provider_options.go
  vendor/github.com/palantir/witchcraft-go-logging/wlog/tcpjson/envelope.go
  vendor/github.com/palantir/witchcraft-go-logging/wlog/tcpjson/tcp_writer.go
  vendor/github.com/palantir/witchcraft-go-logging/wlog/tcpjson/tcp_writer_options.go
  vendor/modules.txt
  witchcraft/internal/tcpjson/async_writer_test.go
  witchcraft/internal/tcpjson/conn_provider_test.go
  witchcraft/internal/tcpjson/tcp_logger_test.go
  witchcraft/witchcraft.go
Labels: merge when ready, no changelog

#275 Touch up metric logger logic
  witchcraft/server_metrics.go
Labels: merge when ready, no changelog

#274 Log metrics that go from 0 to 1
  changelog/@unreleased/pr-274.v2.yml
  go.mod
  integration/metrics_test.go
  witchcraft/server_metrics.go
Labels: autorelease, merge when ready
