Repository palantir/witchcraft-go-server, pull requests merged in 2024-10, with the labels that each got.

#845 Allow dot in path segments
  changelog/@unreleased/pr-845.v2.yml
  wrouter/README.md
  wrouter/pathtemplate.go
  wrouter/pathtemplate_test.go
Labels: merge when ready, autorelease

#848 Improvement: Avoid server shutdown race conditions by adding new ServerShutdownInProgress state
  changelog/@unreleased/pr-848.v2.yml
  witchcraft/server_state.go
  witchcraft/witchcraft.go
  witchcraft/witchcraft_test.go
Labels: merge when ready, autorelease

#850 Add GoroutinesV2 diagnostic handler for emitting goroutine pprofs
  changelog/@unreleased/pr-850.v2.yml
  witchcraft/internal/wdebug/handlers.go
  witchcraft/internal/wdebug/resource_test.go
Labels: autorelease

#851 Upgrade go to 1.22
  .palantir/go-version
  go.mod
Labels: no changelog, merge when ready
